image: alpine:latest

stages:
- echo

echo:
  stage: echo
  script:
  - echo ${CI_PIPELINE_ID}
  - echo ${CI_JOB_STAGE}
  - echo ${CI_JOB_ID}
  artifacts:
    when:
      always
  only:
  - main
  
allowed_fail:
  stage: echo
  script: 
  - /bin/waaaaaaaat
  allow_failure: true
  only:
  - main
