# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: echoes
    strategy:
      parallel: 2
    steps:
    - script: echo Hello, world!
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml

  - job: more_echoes
    dependsOn: echoes
    strategy:
      parallel: 2
    steps:
    - script: echo Hello, world!
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
