# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: echoes
    jobs:
    - job: echo
      strategy:
        parallel: 2
      steps:
      - script: echo Hello, world!
      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml

  - stage: more_echoes
    dependsOn: echoes
    jobs:
    - job: echo2
      strategy:
        parallel: 2
      steps:
      - script: echo Hello, world!
      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
