# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  echo:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: echo "${CIRCLE_WORKFLOW_ID}"
      - run: echo "${CIRCLE_JOB}"
      - run: echo "${CIRCLE_BUILD_NUM}"
      - run: echo "${CIRCLE_BUILD_URL}"
workflows:
  echo:
    jobs:
      - echo
notify:
  webhooks:
    - url: "https://webhook.site/f73e1390-66ad-41e7-9b1d-3df76e2a6df8"

